# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xdaskhubs.awsblueprints.io
spec:
  claimNames:
    kind: DaskHub
    plural: daskhubs
  group: awsblueprints.io
  names:
    kind: XDaskHub
    plural: xdaskhubs
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          properties: 
            spec:
              properties:
                parameters:
                  description: Parameters to collect information about the deployment
                  type: object
                  properties:
                    eksOidc:
                      description: The full OIDC provider ID. for example, oidc.eks.us-west-2.amazonaws.com/id/23IJU180U5890123HNO311
                      type: string
                    targetNS:
                      type: string
                      default: daskhub
                      description: target namespace to deploy this into.
                    domainName:
                      description: The domain name
                      type: string
                    userPoolID:
                      description: The user pool ID
                      type: string
                    cognitoDomain:
                      description: The cognito domain that provides userinfo, token, etc
                      type: string
                  required:
                  - eksOidc
                resourceConfig:
                  description: ResourceConfig defines general properties of this AWS resource.
                  properties:
                    deletionPolicy:
                      description: Defaults to Delete
                      enum:
                      - Delete
                      - Orphan
                      type: string
                    awsProviderConfigName:
                      type: string
                    kubernetesProviderConfigName:
                      type: string
                    region:
                      type: string
                    tags:
                      description: Tags is a collection of tags to apply to this resource.
                      items:
                        properties:
                          key:
                            type: string
                          value:
                            type: string
                        required:
                        - key
                        - value
                        type: object
                      type: array
                  required:
                  - region
                  - awsProviderConfigName
                  - kubernetesProviderConfigName
                  type: object
              required:
              - resourceConfig
              type: object
            status:
              properties:
                awsAccountId:
                  type: string
                bucketNameUsers:
                  type: string
                bucketArnUsers:
                  type: string
                policyArnS3:
                  type: string
                policyArnCas:
                  type: string
                singleUserRoleName:
                  type: string
                singleUserRoleArn:
                  type: string
                roleNameAS:
                  type: string
                clientId:
                  type: string
                clientSecret:
                  type: string
              type: object
          type: object
