# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xvpcsubnets.network.awsblueprints.io  # must be spec.names.plural+"."+spec.group
spec:
  group: network.awsblueprints.io
  names:
    kind: XVpcSubnet        # cluster scope type
    plural: xvpcsubnets     # lowercase only
  claimNames:               # namespace scope type
    kind: vpcSubnet
    plural: vpcsubnets      # lowercase only

  versions:
    - name: v1alpha1
      additionalPrinterColumns:
      - jsonPath: .status.conditions[?(@.type=='Ready')].status
        name: READY
        type: string
      - jsonPath: .status.conditions[?(@.type=='Synced')].status
        name: SYNCED
        type: string
      - jsonPath: .metadata.creationTimestamp
        name: AGE
        type: date
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                networkId:
                  description: ID of this network which other objects can use to reference it. VPC and subnets are labelled with this ID in label 'network.awsblueprints.io/network-id'
                  type: string
                  default: ""
                parameters:
                  description: VPC Input parameters
                  type: object
                  properties:
                    # VPC
                    vpc-cidrBlock:
                      description: CIDR block for VPC
                      type: string
                    vpc-Name:
                      description: Name of the VPC
                      type: string
                    vpc-enableDnsSupport:
                      description: enable DNS Support
                      type: boolean
                      default: true
                    vpc-enableDnsHostNames:
                      description: enable DNS Hostnames
                      type: boolean
                      default: true
                    vpc-amazonProvidedIpv6CidrBlock:
                      description: Requests an Amazon-provided IPv6 CIDR block with a /56 prefix length for the VPC. You cannot specify the range of IP addresses, or the size of the CIDR block.
                      type: boolean
                      default: false
                    vpc-instanceTenancy:
                      description: The allowed tenancy of instances launched into the VPC.
                      type: string
                    vpc-ipv6CidrBlock:
                      description: The IPv6 CIDR block from the IPv6 address pool. You must also specify Ipv6Pool in the request. To let Amazon choose the IPv6 CIDR block for you, omit this parameter.
                      type: string
                    vpc-ipv6Pool:
                      description: The ID of an IPv6 address pool from which to allocate the IPv6 CIDR block.
                      type: string
                    # Public Subnet1
                    publicSubnet1-cidrBlock:
                      description: CIDR block for public subnet 1
                      type: string
                    publicSubnet1-ipv6CIDRBlock:
                      description: ipv6 CIDR block for public subnet 1
                      type: string
                    publicSubnet1-availabilityZone:
                      description: AZ for public subnet 1
                      type: string
                      default: eu-west-1a
                    # Public Subnet2
                    publicSubnet2-cidrBlock:
                      description: CIDR block for public subnet2
                      type: string
                    publicSubnet2-ipv6CIDRBlock:
                      description: ipv6 CIDR block for public subnet2
                      type: string
                    publicSubnet2-availabilityZone:
                      description: AZ for public subnet2
                      type: string
                      default: eu-west-1b
                    # Public Subnet3
                    publicSubnet3-cidrBlock:
                      description: CIDR block for public subnet3
                      type: string
                    publicSubnet3-ipv6CIDRBlock:
                      description: ipv6 CIDR block for public subnet3
                      type: string
                    publicSubnet3-availabilityZone:
                      description: AZ for public subnet3
                      type: string
                      default: eu-west-1c
                    # Private Subnet1
                    privateSubnet1-cidrBlock:
                      description: CIDR block for public subnet 1
                      type: string
                    privateSubnet1-ipv6CIDRBlock:
                      description: ipv6 CIDR block for public subnet 1
                      type: string
                    privateSubnet1-availabilityZone:
                      description: AZ for public subnet 1
                      type: string
                      default: eu-west-1a
                    # Private Subnet2
                    privateSubnet2-cidrBlock:
                      description: CIDR block for public subnet2
                      type: string
                    privateSubnet2-ipv6CIDRBlock:
                      description: ipv6 CIDR block for public subnet2
                      type: string
                    privateSubnet2-availabilityZone:
                      description: AZ for public subnet2
                      type: string
                      default: eu-west-1b
                    # Private Subnet3
                    privateSubnet3-cidrBlock:
                      description: CIDR block for public subnet3
                      type: string
                    privateSubnet3-ipv6CIDRBlock:
                      description: ipv6 CIDR block for public subnet3
                      type: string
                    privateSubnet3-availabilityZone:
                      description: AZ for public subnet3
                      type: string
                      default: eu-west-1c
                    # NAT Gateway
                    nat-connectivityType:
                      description: NAT gateway Connectivity type(public/private)
                      type: string
                      default: public
                  required:
                    - vpc-cidrBlock
                    - vpc-Name
                    - publicSubnet1-cidrBlock
                    - publicSubnet2-cidrBlock
                    - publicSubnet3-cidrBlock
                    - privateSubnet1-cidrBlock
                    - privateSubnet2-cidrBlock
                    - privateSubnet3-cidrBlock
                resourceConfig:
                  description: ResourceConfig defines general properties of this AWS
                    resource.
                  type: object
                  properties:

                    deletionPolicy:
                      description: Defaults to Delete
                      enum:
                        - Delete
                        - Orphan
                      type: string
                      name:
                        description: Set the name of this resource in AWS to the value
                          provided by this field.
                        type: string
                    providerConfigName:
                      type: string
                    region:
                      type: string

                  required:
                    - providerConfigName
                    - region
              required:
                - parameters
                - resourceConfig
          required:
            - spec
