# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0

apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: s3bucket.jet.awsblueprints.io
  labels:
    awsblueprints.io/provider: jet-aws
    awsblueprints.io/environment: dev
    s3.awsblueprints.io/configuration: with-kms
    service: s3
spec:
  writeConnectionSecretsToNamespace: crossplane-system
  compositeTypeRef:
    apiVersion: jet.awsblueprints.io/v1alpha1
    kind: XS3Bucket
  patchSets:
    - name: common-fields
      patches:
        - type: FromCompositeFieldPath
          fromFieldPath: spec.resourceConfig.providerConfigName
          toFieldPath: spec.providerConfigRef.name
        - type: FromCompositeFieldPath
          fromFieldPath: spec.resourceConfig.deletionPolicy
          toFieldPath: spec.deletionPolicy
        - type: FromCompositeFieldPath
          fromFieldPath: spec.resourceConfig.region
          toFieldPath: spec.forProvider.region
        - type: FromCompositeFieldPath
          fromFieldPath: spec.resourceConfig.name
          toFieldPath: metadata.annotations[crossplane.io/external-name]
  resources:
    - name: s3-bucket
      connectionDetails:
        - name: bucket-name
          fromConnectionSecretKey: endpoint
        - name: region
          fromConnectionSecretKey: region
      base:
        apiVersion: s3.aws.jet.crossplane.io/v1alpha2
        kind: Bucket
        spec:
          deletionPolicy: Delete
          forProvider:
            acl: private
            region: eu-west-1
            forceDestroy: false
            serverSideEncryptionConfiguration:
              - rule:
                - applyServerSideEncryptionByDefault:
                    - sseAlgorithm: aws:kms
                      kmsMasterKeyIdSelector:
                        matchControllerRef: true
                        matchLabels:
                          role: s3-bucket-kmskey
      patches:
        - type: PatchSet
          patchSetName: common-fields
        - type: FromCompositeFieldPath
          fromFieldPath: spec.resourceConfig.tags
          toFieldPath: spec.forProvider.tags
        - fromFieldPath: spec.writeConnectionSecretToRef.namespace
          toFieldPath: spec.writeConnectionSecretToRef.namespace
        - type: ToCompositeFieldPath
          fromFieldPath: metadata.annotations[crossplane.io/external-name]
          toFieldPath: status.bucketName
        - type: ToCompositeFieldPath
          fromFieldPath: status.atProvider.arn
          toFieldPath: status.bucketArn
        - fromFieldPath: metadata.uid
          toFieldPath: spec.writeConnectionSecretToRef.name
          transforms:
            - type: string
              string:
                fmt: "%s-bucket"

    - name: kms-key
      base:
        apiVersion: kms.aws.jet.crossplane.io/v1alpha2
        kind: Key
        metadata:
          labels:
            role: s3-bucket-kmskey
        spec:
          deletionPolicy: Delete
          forProvider:
            region: eu-west-1
            description: KMS Key for S3 buckets
            deletionWindowInDays: 7
            tags:
      patches:
        - type: PatchSet
          patchSetName: common-fields
        - type: FromCompositeFieldPath
          fromFieldPath: spec.resourceConfig.tags
          toFieldPath: spec.forProvider.tags
