# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

# Run `kubectl apply -f kms.yaml` to test this example once you bootstrap the EKS cluster with Crossplane and Terrajet AWS Provider
---
apiVersion: kms.aws.jet.crossplane.io/v1alpha2
kind: Key
metadata:
  name: jet-cp-kms-key
spec:
  forProvider:
    region: eu-west-1
    description: KMS Key for S3 buckets
    deletionWindowInDays: 7
    tags:
      Name: jet-cp-kms-key
      awsblueprints.io/environment: dev
  providerConfigRef:
    name: jet-aws-provider-config
