# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

# Run `kubectl apply -f vpc.yaml` to test this example once you bootstrap the EKS cluster with Crossplane and Terrajet AWS Provider
---
apiVersion: ec2.aws.jet.crossplane.io/v1alpha2
kind: VPC
metadata:
  name: jet-aws-provider-vpc
spec:
  forProvider:
    region: eu-west-1
    enableDnsHostnames: true
    enableDnsSupport: true
    enableClassiclink: true
    cidrBlock: 10.30.0.0/16
    enableClassiclinkDnsSupport: true
    tags:
      Name: jet-aws-provider-vpc
      awsblueprints.io/environment: dev
  providerConfigRef:
    name: jet-aws-provider-config
