apiVersion: awsblueprints.io/v1alpha1
kind: FirehoseApp
metadata:
  name: $CLAIM_NAME
  namespace: default
  labels:
    firehoseapps.awsblueprints.io/app: firehose # required for DeliveryStream to contain this label
spec:
  name: "dynatrace"
  envVariables: {}
  resourceConfig:
    providerConfigName: aws-provider-config
    region: $REGION
  environmentConfigs: dev # This allows to use data from EnvironmentConfig
