apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: s3-irsa-app
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: examples/upbound-aws-provider/composite-resources/s3-irsa/helm-chart/
    repoURL: https://github.com/awslabs/crossplane-on-eks.git
    targetRevision: HEAD
    helm:
      values: |- 
        s3irsa:
          enabled: true
  syncPolicy: {}
