
# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0

apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: xsqslambdas3.awsblueprints.io
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
  labels:
    awsblueprints.io/provider: aws
    awsblueprints.io/environment: dev
    serverless.awsblueprints.io/app: sqs-lambda-s3
spec:
  compositeTypeRef:
    apiVersion: awsblueprints.io/v1alpha1
    kind: XServerlessApp
  patchSets:
    - name: common-fields-composition
      patches:
        - type: FromCompositeFieldPath
          fromFieldPath: spec.resourceConfig
          toFieldPath: spec.resourceConfig
    - name: common-lambda
      patches:
        - type: FromCompositeFieldPath
          fromFieldPath: status.bucketName
          toFieldPath: spec.envVariables[APP__CONFIG__DESTINATIONBUCKET]
          policy:
            fromFieldPath: Required
            mergeOptions:
              keepMapValues: true
        - type: FromCompositeFieldPath
          fromFieldPath: status.bucketName
          toFieldPath: spec.envVariables[APP__CONFIG__DESTINATIONQUEUE]
          policy:
            fromFieldPath: Required
            mergeOptions:
              keepMapValues: true
  resources:
    - name: sqs
      base:
        apiVersion: awsblueprints.io/v1alpha1
        kind: XQueue
        spec:
          compositionSelector:
            matchLabels:
              awsblueprints.io/provider: aws
              awsblueprints.io/environment: dev
      patches:
        - type: PatchSet
          patchSetName: common-fields-composition
        - type: ToCompositeFieldPath
          fromFieldPath: status.queueArn
          toFieldPath: status.sourceQueueArn
    - name: processor-event-source
      base:
        apiVersion: awsblueprints.io/v1alpha1
        kind: EventSourceMapping
        spec:
          compositionSelector:
            matchLabels:
              esm.awsblueprints.io/service: sqs
      patches:
        - type: PatchSet
          patchSetName: common-fields-composition
        - type: FromCompositeFieldPath
          fromFieldPath: status.processorFuncName
          toFieldPath: spec.funcName
          policy:
            fromFieldPath: Required
        - type: FromCompositeFieldPath
          fromFieldPath: status.sourceQueueArn
          toFieldPath: spec.sourceArn
          policy:
            fromFieldPath: Required
    - name: processor-lambda
      base:
        apiVersion: awsblueprints.io/v1alpha1
        kind: XLambdaFunction
        spec:
          compositionSelector:
            matchLabels:
              awsblueprints.io/provider: aws
              awsblueprints.io/environment: dev
              awsblueprints.io/type: zip
          handler: main
          runTime: go1.x
          envVariables:
            APP__CONFIG__PROCESSOR: "TRUE"
      patches:
        - type: PatchSet
          patchSetName: common-fields-composition
        - type: PatchSet
          patchSetName: common-lambda
        - type: FromCompositeFieldPath
          fromFieldPath: spec.bucketName
          toFieldPath: spec.bucketName
        - type: FromCompositeFieldPath
          fromFieldPath: spec.bucketKey
          toFieldPath: spec.bucketKey
        - type: FromCompositeFieldPath
          fromFieldPath: spec.memorySize
          toFieldPath: spec.memorySize
        - type: FromCompositeFieldPath
          fromFieldPath: metadata.name
          toFieldPath: metadata.name
          transforms:
            - type: string
              string:
                fmt: "%s-processor"
        - type: ToCompositeFieldPath
          fromFieldPath: status.functionRoleName
          toFieldPath: status.processorRoleName
        - type: ToCompositeFieldPath
          fromFieldPath: status.functionName
          toFieldPath: status.processorFuncName
    - name: bucket
      base:
        apiVersion: awsblueprints.io/v1alpha1
        kind: XObjectStorage
        metadata:
          name: standard-object-storage
        spec:
          compositionSelector:
            matchLabels:
              awsblueprints.io/provider: aws
              awsblueprints.io/environment: dev
              s3.awsblueprints.io/configuration: standard
      patches:
        - type: PatchSet
          patchSetName: common-fields-composition
        - type: ToCompositeFieldPath
          fromFieldPath: status.bucketName
          toFieldPath: status.bucketName
        - type: ToCompositeFieldPath
          fromFieldPath: status.bucketArn
          toFieldPath: status.bucketArn
    - name: processor-bucket-policy
      base:
        apiVersion: awsblueprints.io/v1alpha1
        kind: IAMPolicy
        spec:
          compositionSelector:
            matchLabels:
              awsblueprints.io/provider: aws
              awsblueprints.io/environment: dev
              iam.awsblueprints.io/policy-type: write
              iam.awsblueprints.io/service: s3
      patches:
        - type: PatchSet
          patchSetName: common-fields-composition
        - type: FromCompositeFieldPath
          fromFieldPath: status.processorRoleName
          toFieldPath: spec.roleName
        - type: FromCompositeFieldPath
          fromFieldPath: status.bucketArn
          toFieldPath: spec.resourceArn
    - name: processor-sqs-policy
      base:
        apiVersion: awsblueprints.io/v1alpha1
        kind: IAMPolicy
        spec:
          compositionSelector:
            matchLabels:
              awsblueprints.io/provider: aws
              awsblueprints.io/environment: dev
              iam.awsblueprints.io/policy-type: read
              iam.awsblueprints.io/service: sqs
      patches:
        - type: PatchSet
          patchSetName: common-fields-composition
        - type: FromCompositeFieldPath
          fromFieldPath: status.processorRoleName
          toFieldPath: spec.roleName
        - type: FromCompositeFieldPath
          fromFieldPath: status.sourceQueueArn
          toFieldPath: spec.resourceArn
