# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: eventsourcemappings.awsblueprints.io
spec:
  group: awsblueprints.io
  names:
    kind: EventSourceMapping
    plural: eventsourcemappings
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          description: Policy is the Schema for the policies API
          properties:
            spec:
              description: PolicySpec defines the desired state of Policy
              properties:
                sourceArn:
                  type: string
                funcName:
                  type: string
                resourceConfig:
                  description: ResourceConfig defines general properties of this AWS
                    resource.
                  properties:
                    deletionPolicy:
                      description: Defaults to Delete
                      enum:
                      - Delete
                      - Orphan
                      type: string
                    name:
                      description: Set the name of this resource in AWS to the value provided by this field.
                      type: string
                    providerConfigName:
                      type: string
                    region:
                      type: string
                  required:
                  - providerConfigName
                  - region
                  type: object
              required:
              - sourceArn
              - funcName
              - resourceConfig
              type: object
            status:
              description: PolicyStatus defines the observed state of Policy
              properties:
                policyArn:
                  type: string
              type: object
          type: object
