# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

#----------------------------------------------------------------------------------
# Steps to Deploy:
#----------------------------------------------------------------------------------
#    Step1: Deploy VPC and Subnets using the example
#         > kubectl apply -f compositions/aws-provider/vpc-subnets
#         > kubectl apply -f examples/aws-provider/composite-resources/vpc-subnets
#    Step2: Update the Private SubnetIds in the YAML file below
#    Step3: Deploy EKS Cluster
#         > kubectl apply -f compositions/aws-provider/eks
#         > kubectl apply -f examples/aws-provider/composite-resources/eks
#----------------------------------------------------------------------------------

#----------------------------------------------------------------------------------
# This example resource creates the following resources
#     1. EKS Cluster
#     2. EKS Cluster IAM Role
#     3. Attaches EKS Cluster Policies to the IAM Role
#     4. EKS Managed Node group
#     5. IAM Role for EKS Managed Node group
#     6. Attaches EKS Managed Node Policies to the IAM Role
#----------------------------------------------------------------------------------
---
apiVersion: cluster.awsblueprints.io/v1alpha1
kind: amazonEks
metadata:
  name: xplane-eks-cluster
  namespace: default
spec:
  compositionSelector:
    matchLabels:
      awsblueprints.io/provider: aws
      awsblueprints.io/environment: dev
      awsblueprints.io/subnet-selection: id
      service: eks
  resourceConfig:
    providerConfigName: aws-provider-config
    region: eu-west-1
  parameters:
    #EKS Input parameters
    version: "1.21"
    endpointPrivateAccess: false
    endpointPublicAccess: true
    subnetIds: # Update your subnet ids
      - "subnet-abc"
      - "subnet-def"
      - "subnet-ghi"
  managedNodeGroups:
    minSize: 2
  writeConnectionSecretToRef:
    name: xplane-eks-cluster
