# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0

apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xamazonekss.cluster.awsblueprints.io  # must be spec.names.plural+"."+spec.group
spec:
  connectionSecretKeys:
    - kubeconfig
    - cluster-ca
    - apiserver-endpoint
  group: cluster.awsblueprints.io
  names:
    kind: XAmazonEks        # cluster scope type
    plural: xamazonekss
  claimNames:               # namespace scope type
    kind: amazonEks
    plural: amazonekss      # lowercase only

  versions:
    - name: v1alpha1
      additionalPrinterColumns:
      - jsonPath: .status.conditions[?(@.type=='Ready')].status
        name: READY
        type: string
      - jsonPath: .status.conditions[?(@.type=='Synced')].status
        name: SYNCED
        type: string
      - jsonPath: .metadata.creationTimestamp
        name: AGE
        type: date
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                parameters:
                  description: EKS Input parameters
                  type: object
                  properties:

                    version:
                      description: Kubernetes Version
                      type: string
                      enum: [ "1.21", "1.22" ]
                    endpointPrivateAccess:
                      description: endpointPrivateAccess
                      type: boolean
                      default: false
                    endpointPublicAccess:
                      description: endpointPublicAccess
                      type: boolean
                      default: true
                    subnetIds:
                      description: EKS Cluster Subnet Id references
                      items:
                        type: string
                      type: array
                  required:
                    - version
                    - subnetIds
                managedNodeGroups:
                  description: Managed Node Groups properties
                  type: object
                  properties:

                    minSize:
                      type: integer
                      description: Nodegroup Min Size.
                    desiredSize:
                      type: integer
                      description: Nodegroup desiredSize.
                      default: 3
                    maxSize:
                      type: integer
                      description: Nodegroup maxSize.
                      default: 10
                    amiType:
                      type: string
                      description: AMI Type.
                      enum:
                        - AL2_x86_64_GPU
                        - AL2_x86_64
                        - AL2_ARM_64
                        - BOTTLEROCKET_x86_64
                        - BOTTLEROCKET_ARM_64
                      default: AL2_x86_64
                    capacityType:
                      type: string
                      description: Capacity Type.
                      enum:
                        - ON_DEMAND
                        - SPOT
                      default: ON_DEMAND
                    instanceTypes:
                      items:
                        type: string
                      type: array
                      description: Instance Type.
                      default:
                       - m5.large
                  required:
                    - minSize
                resourceConfig:
                  description: ResourceConfig defines general properties of this AWS
                    resource.
                  type: object
                  properties:

                    deletionPolicy:
                      description: Defaults to Delete
                      enum:
                        - Delete
                        - Orphan
                      type: string
                      name:
                        description: Set the name of this resource in AWS to the value
                          provided by this field.
                        type: string
                    providerConfigName:
                      type: string
                    region:
                      type: string

                  required:
                    - providerConfigName
                    - region
              required:
                - parameters
                - resourceConfig
                - managedNodeGroups
          required:
            - spec
