# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0

apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: xamazonekss.cluster.awsblueprints.io
  labels:
    awsblueprints.io/provider: aws
    awsblueprints.io/environment: dev
    awsblueprints.io/subnet-selection: id
    crossplane.io/xrd: xamazonekss.cluster.awsblueprints.io
    service: eks
spec:
  writeConnectionSecretsToNamespace: crossplane-system
  compositeTypeRef:
    apiVersion: cluster.awsblueprints.io/v1alpha1
    kind: XAmazonEks

  patchSets:
    - name: common-parameters
      patches:
        - type: FromCompositeFieldPath
          fromFieldPath: spec.resourceConfig.providerConfigName
          toFieldPath: spec.providerConfigRef.name
        - type: FromCompositeFieldPath
          fromFieldPath: spec.resourceConfig.deletionPolicy
          toFieldPath: spec.deletionPolicy
        - type: FromCompositeFieldPath
          fromFieldPath: spec.resourceConfig.region
          toFieldPath: spec.forProvider.region
#        - type: FromCompositeFieldPath
#          fromFieldPath: spec.resourceConfig.name
#          toFieldPath: metadata.annotations[crossplane.io/external-name]

  resources:
    - name: eks-cluster
      base:
        apiVersion: eks.aws.crossplane.io/v1beta1
        kind: Cluster
        metadata:
          labels:
            role: controlplane
        spec:
          forProvider:
            version:
            roleArnSelector:
              matchControllerRef: true
              matchLabels:
                role: controlplane
            resourcesVpcConfig:
              endpointPrivateAccess:
              endpointPublicAccess:
              subnetIds:
          writeConnectionSecretToRef:
            namespace: crossplane-system
      patches:
        - type: PatchSet
          patchSetName: common-parameters
        - fromFieldPath: metadata.annotations[crossplane.io/external-name]
          toFieldPath: metadata.annotations[crossplane.io/external-name]
        - fromFieldPath: spec.parameters.version
          toFieldPath: spec.forProvider.version
        - fromFieldPath: spec.parameters.subnetIds
          toFieldPath: spec.forProvider.resourcesVpcConfig.subnetIds
        - fromFieldPath: spec.parameters.endpointPrivateAccess
          toFieldPath: spec.forProvider.resourcesVpcConfig.endpointPrivateAccess
        - fromFieldPath: spec.parameters.endpointPublicAccess
          toFieldPath: spec.forProvider.resourcesVpcConfig.endpointPublicAccess
        - fromFieldPath: metadata.uid
          toFieldPath: spec.writeConnectionSecretToRef.name
          transforms:
            - type: string
              string:
                fmt: "%s-eks-cluster-conn"
        - fromFieldPath: spec.writeConnectionSecretToRef.namespace
          toFieldPath: spec.writeConnectionSecretToRef.namespace
#        - type: ToCompositeFieldPath
#          fromFieldPath: status.atProvider.identity.oidc.issuer
#          toFieldPath: status.eks.oidc
#          policy:
#            fromFieldPath: Optional
      connectionDetails:
        - name: cluster-ca
          fromConnectionSecretKey: clusterCA
        - name: apiserver-endpoint
          fromConnectionSecretKey: endpoint
        - name: kubeconfig
          fromConnectionSecretKey: kubeconfig
    - name: eks-cluster-role
      base:
        apiVersion: iam.aws.crossplane.io/v1beta1
        kind: Role
        metadata:
          labels:
            role: controlplane
        spec:
          forProvider:
            assumeRolePolicyDocument: |
              {
                "Version": "2012-10-17",
                "Statement": [
                    {
                        "Effect": "Allow",
                        "Principal": {
                            "Service": [
                                "eks.amazonaws.com"
                            ]
                        },
                        "Action": [
                            "sts:AssumeRole"
                        ]
                    }
                ]
              }
      patches:
        - type: PatchSet
          patchSetName: common-parameters
    - name: eks-cluster-policy
      base:
        apiVersion: iam.aws.crossplane.io/v1beta1
        kind: RolePolicyAttachment
        spec:
          forProvider:
            policyArn: arn:aws:iam::aws:policy/AmazonEKSClusterPolicy
            roleNameSelector:
              matchControllerRef: true
              matchLabels:
                role: controlplane
      patches:
        - type: PatchSet
          patchSetName: common-parameters
    - name: eks-service-policy
      base:
        apiVersion: iam.aws.crossplane.io/v1beta1
        kind: RolePolicyAttachment
        spec:
          forProvider:
            policyArn: arn:aws:iam::aws:policy/AmazonEKSServicePolicy
            roleNameSelector:
              matchControllerRef: true
              matchLabels:
                role: controlplane
      patches:
        - type: PatchSet
          patchSetName: common-parameters
    - name: eks-vpcresource-controller-policy
      base:
        apiVersion: iam.aws.crossplane.io/v1beta1
        kind: RolePolicyAttachment
        spec:
          forProvider:
            policyArn: arn:aws:iam::aws:policy/AmazonEKSVPCResourceController
            roleNameSelector:
              matchControllerRef: true
              matchLabels:
                role: controlplane
      patches:
        - type: PatchSet
          patchSetName: common-parameters

# EKS Managed Node groups
    - name: eks-managed-nodegroups
      base:
        apiVersion: eks.aws.crossplane.io/v1alpha1
        kind: NodeGroup
        spec:
          forProvider:
            amiType:
            clusterNameSelector:
              matchControllerRef: true
              matchLabels:
                role: controlplane
            nodeRoleSelector:
              matchControllerRef: true
              matchLabels:
                role: managed-nodegroup
            subnets:
            scalingConfig:
              minSize:
              desiredSize:
              maxSize:
            capacityType:
            instanceTypes:
      patches:
        - type: PatchSet
          patchSetName: common-parameters
        - fromFieldPath: metadata.annotations[crossplane.io/external-name]
          toFieldPath: metadata.annotations[crossplane.io/external-name]
        - fromFieldPath: spec.managedNodeGroups.minSize
          toFieldPath: spec.forProvider.scalingConfig.minSize
        - fromFieldPath: spec.managedNodeGroups.maxSize
          toFieldPath: spec.forProvider.scalingConfig.maxSize
        - fromFieldPath: spec.managedNodeGroups.desiredSize
          toFieldPath: spec.forProvider.scalingConfig.desiredSize
        - fromFieldPath: spec.managedNodeGroups.desiredSize
          toFieldPath: spec.forProvider.scalingConfig.desiredSize
        - fromFieldPath: spec.managedNodeGroups.capacityType
          toFieldPath: spec.forProvider.capacityType
        - fromFieldPath: spec.managedNodeGroups.instanceTypes
          toFieldPath: spec.forProvider.instanceTypes
        - fromFieldPath: spec.managedNodeGroups.amiType
          toFieldPath: spec.forProvider.amiType
        - fromFieldPath: spec.parameters.subnetIds
          toFieldPath: spec.forProvider.subnets

    - name: eks-managed-nodegroup-iam-role
      base:
        apiVersion: iam.aws.crossplane.io/v1beta1
        kind: Role
        metadata:
          labels:
            role: managed-nodegroup
        spec:
          forProvider:
            assumeRolePolicyDocument: |
              {
                "Version": "2012-10-17",
                "Statement": [
                    {
                        "Effect": "Allow",
                        "Principal": {
                            "Service": [
                                "ec2.amazonaws.com"
                            ]
                        },
                        "Action": [
                            "sts:AssumeRole"
                        ]
                    }
                ]
              }
      patches:
        - type: PatchSet
          patchSetName: common-parameters
    - name: eks-managed-nodegroup-worker-node-policy
      base:
        apiVersion: iam.aws.crossplane.io/v1beta1
        kind: RolePolicyAttachment
        spec:
          forProvider:
            policyArn: arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
            roleNameSelector:
              matchControllerRef: true
              matchLabels:
                role:  managed-nodegroup
      patches:
        - type: PatchSet
          patchSetName: common-parameters
    - name: eks-managed-nodegroup-container-registry-policy
      base:
        apiVersion: iam.aws.crossplane.io/v1beta1
        kind: RolePolicyAttachment
        spec:
          forProvider:
            policyArn: arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly
            roleNameSelector:
              matchControllerRef: true
              matchLabels:
                role: managed-nodegroup
      patches:
        - type: PatchSet
          patchSetName: common-parameters
    - name: eks-managed-nodegroup-ssm-policy
      base:
        apiVersion: iam.aws.crossplane.io/v1beta1
        kind: RolePolicyAttachment
        spec:
          forProvider:
            policyArn: arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
            roleNameSelector:
              matchControllerRef: true
              matchLabels:
                role: managed-nodegroup
      patches:
        - type: PatchSet
          patchSetName: common-parameters
    - name: eks-managed-nodegroup-cni-policy
      base:
        apiVersion: iam.aws.crossplane.io/v1beta1
        kind: RolePolicyAttachment
        spec:
          forProvider:
            policyArn: arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
            roleNameSelector:
              matchControllerRef: true
              matchLabels:
                role: managed-nodegroup
      patches:
        - type: PatchSet
          patchSetName: common-parameters
