# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

apiVersion: awsblueprints.io/v1alpha1
kind: DynamoDBTable
metadata:
  name: test-table-provisioned-composite-key-gsi
  namespace: default
spec:
  compositionSelector:
    matchLabels:
      awsblueprints.io/provider: aws
      awsblueprints.io/environment: dev
      dynamodb.awsblueprints.io/capacity: provisioned
      dynamodb.awsblueprints.io/pkType: composite
      dynamodb.awsblueprints.io/secondaryIndex: global
      dynamodb.awsblueprints.io/secondaryIndexCount: "1"
  publishConnectionDetailsTo:
    name: test-table-provisioned-composite-key-gsi
  resourceConfig:
    providerConfigName: aws-provider-config
    region: us-west-2
    tags:
      - key: env
        value: test
      - key: anotherKey
        value: anotherValue
  tableIndex:
    hashKeyName: hashKey
    hashKeyType: S
    rangeKeyName: rangeKey
    rangeKeyType: S
  throughputConfig:
    read: 7
    write: 4
  globalSecondaryIndices:
    - keySchema:
        hashKeyName: hashKeyGSI
        hashKeyType: S
        rangeKeyName: rangeKeyGSI
        rangeKeyType: S
      name: gsiExample
      throughputConfig:
        read: 7
        write: 4
