apiVersion: awsblueprints.io/v1alpha1
kind: SubscriptionFilter
metadata:
  name: test-logs-firehose-s3-lambda
  namespace: default
spec:
  compositionSelector:
    matchLabels:
      awsblueprints.io/provider: aws
      awsblueprints.io/environment: dev
      cloudwatchlogs.awsblueprints.io/service: cloudwatch
      cloudwatchlogs.awsblueprints.io/logs: subscriptionfilter
  # For now specified the Kinesis Firehose Stream arn
  destinationArn: "arn:aws:firehose:${AWS_REGION}:${AWS_ACCOUNT_ID}:deliverystream/<firehose delivery stream name>"
  # TODO there is an issue with destinationArnSelector not working for Kinesis Firehose https://github.com/upbound/upjet/issues/95
  #destinationArnSelector:
  #  matchLabels:
  #    crossplane.io/claim-name: test-logs-firehose-s3-lambda
  #    crossplane.io/claim-namespace: default
  #    firehoseapps.awsblueprints.io/app: firehose
  logGroupName: "/aws/eks/crossplane-blueprints/cluster"
  filterPattern: ""
  roleArnSelector:
    matchLabels:
      crossplane.io/claim-name: test-logs-firehose-s3-lambda
      crossplane.io/claim-namespace: default
      iam.awsblueprints.io/service: firehose
  resourceConfig:
    providerConfigName: aws-provider-config
    region: us-east-1


