apiVersion: constraints.gatekeeper.sh/v1beta1
kind: AwsRequiredTags
metadata:
  name: awsrequiredtags
spec:
  match:
    kinds:
      - apiGroups: ["*"]
        kinds: ["*"]
  parameters:
    tags: ["owner"]