apiVersion: dynamodb.aws.upbound.io/v1beta1
kind: Table
metadata:
  annotations:
    meta.upbound.io/example-id: dynamodb/v1beta1/globaltable
  name: finance-table
spec:
  providerConfigRef:
    name: aws-provider-config
  forProvider:
    attribute:
      - name: myAttribute
        type: S
    hashKey: myAttribute
    readCapacity: 1
    writeCapacity: 1
    region: eu-west-2
    tags:
      owner: finance