# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: manage-dynamodb.iampolicy.awsblueprints.io
  labels:
    awsblueprints.io/provider: aws
    awsblueprints.io/environment: dev
    iam.awsblueprints.io/policy-type: manage
    iam.awsblueprints.io/service: dynamodb
spec:
  writeConnectionSecretsToNamespace: crossplane-system
  compositeTypeRef:
    apiVersion: awsblueprints.io/v1alpha1
    kind: IAMPolicy
  patchSets:
    - name: common-fields
      patches:
        - type: FromCompositeFieldPath
          fromFieldPath: spec.resourceConfig.providerConfigName
          toFieldPath: spec.providerConfigRef.name
        - type: FromCompositeFieldPath
          fromFieldPath: spec.resourceConfig.deletionPolicy
          toFieldPath: spec.deletionPolicy
        - type: FromCompositeFieldPath
          fromFieldPath: spec.resourceConfig.name
          toFieldPath: metadata.annotations[crossplane.io/external-name]
        - type: FromCompositeFieldPath
          fromFieldPath: spec.resourceConfig.tags
          toFieldPath: spec.forProvider.tags
          policy:
            mergeOptions:
              appendSlice: true
              keepMapValues: true
  resources:
    - name: manage-policy
      base:
        apiVersion: iam.aws.crossplane.io/v1beta1
        kind: Policy
        spec:
          deletionPolicy: Delete
          forProvider:
            name: ""
            document: ""
      patches:
        - type: PatchSet
          patchSetName: common-fields
        - type: ToCompositeFieldPath
          fromFieldPath: metadata.annotations[crossplane.io/external-name]
          toFieldPath: status.policyArn
        - type: CombineFromComposite
          toFieldPath: spec.forProvider.name
          combine:
            variables:
              - fromFieldPath: metadata.name
            strategy: string
            string:
              fmt: "%s-dynamodb-table-read-policy"
        - type: CombineFromComposite
          toFieldPath: spec.forProvider.document
          combine:
            variables:
            - fromFieldPath: spec.resourceArn
            - fromFieldPath: spec.resourceArn
            strategy: string
            string:
              fmt: |
                {
                  "Version": "2012-10-17",
                  "Statement": [
                    {
                      "Effect": "Allow",
                      "Action": [
                        "dynamodb:*",
                      ],
                      "Resource": [
                        "%s",
                        "%s/index/*",
                        "%s/stream/*",
                        "%s/backup/*",
                        "%s/global-table/*",
                        "%s/export/*"
                      ]
                    },
                    {
                      "Effect": "Allow",
                      "Action": [
                        "dynamodb:ListTables",
                        "dynamodb:ListStreams",
                        "dynamodb:ListGlobalTables"
                      ],
                      "Resource": [
                        "*"
                      ]
                    }
                  ]
                }
