name: 🐞 Bug Report
title: "[Bug]: <title>"
description: Create a report to help us improve
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        ### How to write a good bug report?

        - Respect the issue template as much as possible.
        - The title should be short and descriptive.
        - Explain the conditions which led you to report this issue and the context.
        - The context should lead to something, an idea or a problem that you’re facing.
        - Remain clear and concise.
        - Format your messages to help the reader focus on what matters and understand the structure of your message, use [Markdown syntax](https://help.github.com/articles/github-flavored-markdown)

  - type: checkboxes
    id: terms
    attributes:
      label: Welcome to AWS Blueprints for Crossplane!
      options:
        - label: Yes, I've searched similar issues on [GitHub](https://github.com/aws-samples/crossplane-aws-blueprints/issues) and didn't find any.
          required: true

  - type: input
    attributes:
      label: AWS Blueprints for Crossplane Release version
      description: |
        `latest` is not considered as a valid version.
        Enter release number!
      placeholder: Your version here.
    validations:
      required: true

  - type: textarea
    attributes:
      label: What is your environment, configuration and the example used?
      description: |
        link to example used from this repo  etc.

        Use [Markdown syntax](https://help.github.com/articles/github-flavored-markdown) if needed.
      placeholder: Add information here.
    validations:
      required: true

  - type: textarea
    attributes:
      label: What did you do and What did you see instead?
      description: |
        Provide error details and the expected details.

        Use [Markdown syntax](https://help.github.com/articles/github-flavored-markdown) if needed.
      placeholder: Add information here.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Additional Information
      description: Use [Markdown syntax](https://help.github.com/articles/github-flavored-markdown) if needed.
      placeholder: Add information here.
      render: shell
    validations:
      required: false
