# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xfanouts.awsblueprints.io
spec:
  group: awsblueprints.io
  names:
    kind: XFanout
    plural: xfanouts
  claimNames:
    kind: Fanout
    plural: fanouts
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          properties:
            spec:
              properties:
                encryptionKey:
                  type: string
                resourceConfig:
                  description: ResourceConfig defines general properties of this AWS
                    resource.
                  properties:
                    deletionPolicy:
                      description: Defaults to Delete
                      enum:
                      - Delete
                      - Orphan
                      type: string
                    name:
                      description: Set the name of this resource in AWS to the value
                        provided by this field.
                      type: string
                    providerConfigName:
                      type: string
                    region:
                      type: string
                  required:
                  - region
                  type: object
              required:
              - resourceConfig
              type: object
            status:
              properties:
                queueUrl:
                  type: string
                queueArn:
                  type: string
                topicArn:
                  type: string
              type: object
          required:
          - spec
          type: object
