apiVersion: awsblueprints.io/v1alpha1
kind: SubscriptionFilter
metadata:
  name: test-logs-firehose-s3-lambda
  namespace: ${NAMESPACE}
spec:
  forProvider:
    logGroupName: "${CLOUDWATCH_LOG_GROUP}"
    filterPattern: ""
    roleArnSelector:
      matchLabels:
        crossplane.io/claim-name: "${KINESIS_CLAIM_NAME}"
        crossplane.io/claim-namespace: ${NAMESPACE}
        iam.awsblueprints.io/service: firehose
    destinationArn: "${DESTINATION_KINESIS_ARN}"
    # TODO there is an issue with destinationArnSelector not working for Kinesis Firehose https://github.com/upbound/upjet/issues/95
    #destinationArnSelector:
    #  matchLabels:
    #    crossplane.io/claim-name: ${KINESIS_CLAIM_NAME}"
    #    crossplane.io/claim-namespace: default
    #    firehoseapps.awsblueprints.io/app: firehose
  resourceConfig:
    providerConfigName: aws-provider-config
    region: us-east-1


