# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: s3bucket-multi-tenant.awsblueprints.io
  labels:
    awsblueprints.io/provider: aws
    awsblueprints.io/environment: dev
    s3.awsblueprints.io/configuration: standard-multi-tenant
spec:
  publishConnectionDetailsWithStoreConfigRef:
    name: in-cluster
  compositeTypeRef:
    apiVersion: awsblueprints.io/v1alpha1
    kind: XObjectStorage
  patchSets:
    - name: common-fields
      patches:
        - type: FromCompositeFieldPath
          fromFieldPath: spec.resourceConfig.deletionPolicy
          toFieldPath: spec.deletionPolicy
        - type: FromCompositeFieldPath
          fromFieldPath: spec.resourceConfig.region
          toFieldPath: spec.forProvider.region
        - type: FromCompositeFieldPath
          fromFieldPath: spec.resourceConfig.name
          toFieldPath: metadata.annotations[crossplane.io/external-name]
  resources:
    - name: s3-bucket
      connectionDetails:
        - name: bucket-name
          fromConnectionSecretKey: endpoint
        - name: region
          fromConnectionSecretKey: region
      base:
        apiVersion: s3.aws.crossplane.io/v1beta1
        kind: Bucket
        spec:
          deletionPolicy: Delete
          publishConnectionDetailsTo:
            name: to-be-patched
            metadata:
              labels:
                awsblueprints.io/environment: dev
                awsblueprints.io/provider: aws
                awsblueprints.io/composition-name: s3bucket-multi-tenant.awsblueprints.io
            configRef:
              name: vault
          forProvider:
            objectOwnership: BucketOwnerEnforced
            publicAccessBlockConfiguration:
              blockPublicPolicy: true
              restrictPublicBuckets: true
            serverSideEncryptionConfiguration:
              rules:
                - applyServerSideEncryptionByDefault:
                    sseAlgorithm: AES256
      patches:
        - type: PatchSet
          patchSetName: common-fields
        - type: FromCompositeFieldPath
          fromFieldPath: spec.resourceConfig.tags
          toFieldPath: spec.forProvider.tagging.tagSet
          policy:
            mergeOptions:
              appendSlice: true
              keepMapValues: true
        - type: ToCompositeFieldPath
          fromFieldPath: metadata.annotations[crossplane.io/external-name]
          toFieldPath: status.bucketName
        - type: ToCompositeFieldPath
          fromFieldPath: status.atProvider.arn
          toFieldPath: status.bucketArn
        - type: FromCompositeFieldPath
          fromFieldPath: spec.resourceConfig.region
          toFieldPath: spec.forProvider.locationConstraint
        - type: CombineFromComposite
          policy:
            fromFieldPath: Required
          fromFieldPath: metadata.labels[crossplane.io/claim-namespace]
          toFieldPath: spec.providerConfigRef.name
          combine:
            variables:
              - fromFieldPath: metadata.labels[crossplane.io/claim-namespace]
            strategy: string
            string:
              fmt: "%s-provider-config"
        - type: CombineFromComposite
          policy:
            fromFieldPath: Required
          fromFieldPath: metadata.labels[crossplane.io/claim-namespace]
          toFieldPath: spec.publishConnectionDetailsTo.name
          combine:
            variables:
              - fromFieldPath: metadata.labels[crossplane.io/claim-namespace]
            strategy: string
            string:
              fmt: "%s/dev/bucket"
