apiVersion: awsblueprints.io/v1alpha1
kind: ServerlessApp
metadata:
  name: test-serverless
  namespace: default
spec:
  compositionSelector:
    matchLabels:
      awsblueprints.io/provider: aws
      awsblueprints.io/environment: dev
      serverless.awsblueprints.io/app: object-processor
  bucketName: lambda-code-bucket-ab3
  bucketKey: function.zip
  resourceConfig:
    providerConfigName: aws-provider-config
    region: us-east-1
