# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xrelationaldatabases.awsblueprints.io
spec:
  group: awsblueprints.io
  names:
    kind: XRelationalDatabase
    plural: xrelationaldatabases
  claimNames:
    kind: RelationalDatabase
    plural: relationaldatabases
  connectionSecretKeys:
    - username
    - password
    - endpoint
    - port
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          properties:
            spec:
              properties:
                databaseName:
                  type: string
                dbSubnetGroupName:
                  type: string
                engineVersion: 
                  type: string
                storageGB:
                  type: integer
                subnetIds:
                  type: array
                  items:
                    type: string
                  minItems: 1
                vpcId: 
                  type: string
                IngressRules:
                  type: array
                  items:
                    type: object
                    properties:
                      ipProtocol:
                        type: string
                      fromPort:
                        type: integer
                      toPort:
                        type: integer
                      ipRanges:
                        type: array
                        items:
                          type: object
                          properties:
                            cidrIp:
                              type: string
                resourceConfig:
                  description: ResourceConfig defines general properties of this AWS
                    resource.
                  properties:
                    deletionPolicy:
                      description: Defaults to Delete
                      enum:
                      - Delete
                      - Orphan
                      type: string
                    name:
                      description: Set the name of this resource in AWS to the value provided by this field.
                      type: string
                    providerConfigName:
                      type: string
                    region:
                      type: string
                    tags:
                      items:
                        properties:
                          key:
                            type: string
                          value:
                            type: string
                        required:
                        - key
                        - value
                        type: object
                      type: array
                  required:
                  - providerConfigName
                  - region
                  - tags
                  type: object
              required:
              - resourceConfig
              type: object
            status:
              properties:
                securityGroupId:
                  type: string
                clusterId:
                  type: string
              type: object
          type: object

