# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

---
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: xvpcs.network.jet.awsblueprints.io
  labels:
    awsblueprints.io/provider: jet-aws
    awsblueprints.io/environment: dev
    crossplane.io/xrd: xamazonvpcs.network.jet.awsblueprints.io
    service: vpc
    compute: managedamazon-vpc
spec:
  writeConnectionSecretsToNamespace: crossplane-system
  compositeTypeRef:
    apiVersion: network.jet.awsblueprints.io/v1alpha1
    kind: XAmazonVpc

  patchSets:
    - name: common-parameters
      patches:
        - type: FromCompositeFieldPath
          fromFieldPath: spec.resourceConfig.providerConfigName
          toFieldPath: spec.providerConfigRef.name
        - type: FromCompositeFieldPath
          fromFieldPath: spec.resourceConfig.deletionPolicy
          toFieldPath: spec.deletionPolicy
        - type: FromCompositeFieldPath
          fromFieldPath: spec.resourceConfig.region
          toFieldPath: spec.forProvider.region
#        - type: FromCompositeFieldPath
#          fromFieldPath: spec.resourceConfig.name
#          toFieldPath: metadata.annotations[crossplane.io/external-name]

  resources:
    - name: vpc
      base:
        apiVersion: ec2.aws.jet.crossplane.io/v1alpha2
        kind: VPC
        spec:
          forProvider:
            enableDnsSupport: ""
            enableDnsHostnames: ""
            cidrBlock: ""
            tags:
              Name: ""

      patches:
        - type: PatchSet
          patchSetName: common-parameters
        - type: FromCompositeFieldPath
          fromFieldPath: spec.parameters.vpccidrBlock
          toFieldPath: spec.forProvider.cidrBlock
        - type: FromCompositeFieldPath
          fromFieldPath: spec.parameters.vpcName
          toFieldPath: spec.forProvider.tags.Name
        - type: FromCompositeFieldPath
          fromFieldPath: spec.parameters.enableDnsSupport
          toFieldPath: spec.forProvider.enableDnsSupport
        - type: FromCompositeFieldPath
          fromFieldPath: spec.parameters.enableDnsHostnames
          toFieldPath: spec.forProvider.enableDnsHostnames
