# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0

apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xencryptionkeys.awsblueprints.io
spec:
  group: awsblueprints.io
  names:
    kind: XEncryptionKey
    plural: xencryptionkeys
  claimNames:
    kind: EncryptionKey
    plural: encryptionkeys
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          properties:
            spec:
              properties:
                policy:
                  type: string
                resourceConfig:
                  description: ResourceConfig defines general properties of this AWS
                    resource.
                  properties:
                    deletionPolicy:
                      description: Defaults to Delete
                      enum:
                      - Delete
                      - Orphan
                      type: string
                    name:
                      description: Set the name of this resource in AWS to the value
                        provided by this field.
                      type: string
                    providerConfigName:
                      type: string
                    region:
                      type: string
                  required:
                  - region
                  type: object
              required:
              - resourceConfig
              type: object
            status:
              properties:
                keyName:
                  type: string
                keyId:
                  type: string
                keyArn:
                  type: string
              type: object
          required:
          - spec
          type: object
