# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-app
  namespace: "example-app"
spec:
  selector:
    matchLabels:
      app: dynamodb-table-test
  template:
    metadata:
      labels:
        app: dynamodb-table-test
    spec:
      serviceAccountName: example-app
      containers:
      - name: aws-cli
        image: amazon/aws-cli:latest
        env:
          - name: AWS_DEFAULT_REGION
            valueFrom:
              secretKeyRef:
                name: example-application-secrets
                key: region
          - name: TABLE_NAME
            valueFrom:
              secretKeyRef:
                name: example-application-secrets
                key: tableName
          - name: TEST_KEY
            value: '{"hashKey": {"S":"test1"}}'
        command:
          - "/bin/bash"
        args:
          - "-c"
          - 'while true; do echo "putting item"; aws dynamodb put-item --table-name $TABLE_NAME  --item "$TEST_KEY" || exit 10; sleep 120; echo "removing item"; aws dynamodb delete-item --table-name $TABLE_NAME --key "$TEST_KEY"; sleep 120 ; done'