# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

apiVersion: awsblueprints.io/v1alpha1
kind: DaskHub
metadata:
  name: test-daskhub
  namespace: default
spec:
  # compositeDeletePolicy: Foreground
  compositionSelector:
    matchLabels:
      awsblueprints.io/configuration: password
      awsblueprints.io/environment: test
  resourceConfig:
    awsProviderConfigName: aws-provider-config
    kubernetesProviderConfigName: default # update this if you are deploying to another cluster.
    region: us-west-2
  parameters:
    eksOidc: oidc.eks.us-west-2.amazonaws.com/id/123 # update this with your cluster's oidc id.
