apiVersion: awsblueprints.io/v1alpha1
kind: ObjectStorage
metadata:
  name: test-bucket-awsblueprint-112233
  namespace: default
spec:
  resourceConfig:
    providerConfigName: aws-provider-config
    region: us-east-1
