# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: write-dynamodb.iampolicy.awsblueprints.io
  labels:
    awsblueprints.io/provider: aws
    awsblueprints.io/environment: dev
    iam.awsblueprints.io/policy-type: write
    iam.awsblueprints.io/service: dynamodb
spec:
  compositeTypeRef:
    apiVersion: awsblueprints.io/v1alpha1
    kind: IAMPolicy
  patchSets:
    - name: common-fields
      patches:
        - type: FromCompositeFieldPath
          fromFieldPath: spec.resourceConfig.deletionPolicy
          toFieldPath: spec.deletionPolicy
        - type: FromCompositeFieldPath
          fromFieldPath: spec.resourceConfig.providerConfigName
          toFieldPath: spec.providerConfigRef.name
        - fromFieldPath: "metadata.name"
          toFieldPath: "metadata.name"
          transforms:
            - type: string
              string:
                fmt: "policy-dynamodb-write-%s"
  resources:
    - name: write-policy
      base:
        apiVersion: iam.aws.upbound.io/v1beta1
        kind: Policy
        spec:
          deletionPolicy: Delete
          forProvider: {}
      patches:
        - type: PatchSet
          patchSetName: common-fields
        - type: FromCompositeFieldPath
          fromFieldPath: spec.resourceConfig.tags
          toFieldPath: spec.forProvider.tags
          policy:
            mergeOptions:
              keepMapValues: true
        - type: CombineFromComposite
          toFieldPath: spec.forProvider.policy
          combine:
            variables:
            - fromFieldPath: spec.resourceArn
            - fromFieldPath: spec.resourceArn
            - fromFieldPath: spec.resourceArn
            strategy: string
            string:
              fmt: |
                {
                    "Version": "2012-10-17",
                    "Statement": [
                        {
                            "Sid": "ListAndDescribe",
                            "Effect": "Allow",
                            "Action": [
                                "dynamodb:List*",
                                "dynamodb:DescribeReservedCapacity*",
                                "dynamodb:DescribeLimits",
                                "dynamodb:DescribeTimeToLive"
                            ],
                            "Resource": [
                              "%s/*"
                            ]
                        },
                        {
                            "Sid": "SpecificTable",
                            "Effect": "Allow",
                            "Action": [
                                "dynamodb:BatchGet*",
                                "dynamodb:DescribeStream",
                                "dynamodb:DescribeTable",
                                "dynamodb:Query",
                                "dynamodb:Scan",
                                "dynamodb:BatchWrite*",
                                "dynamodb:CreateTable",
                                "dynamodb:Delete*",
                                "dynamodb:Update*",
                                "dynamodb:GetItem",
                                "dynamodb:PutItem"
                            ],
                            "Resource": [
                              "%s/*",
                              "%s"
                            ]
                        }
                    ]
                }
    - name: policy-attachment
      base:
        apiVersion: iam.aws.upbound.io/v1beta1
        kind: RolePolicyAttachment
        spec:
          deletionPolicy: Delete
          forProvider:
            policyArnSelector:
              matchControllerRef: true
      patches:
        - type: PatchSet
          patchSetName: common-fields
        - type: FromCompositeFieldPath
          fromFieldPath: spec.roleName
          toFieldPath: spec.forProvider.role
