apiVersion: awsblueprints.io/v1alpha1
kind: XLambdaFunction
metadata:
  name: test-zip-lambda
spec:
  compositionSelector:
    matchLabels:
      awsblueprints.io/provider: aws-jet
      awsblueprints.io/environment: dev
  resourceConfig:
    jetProviderConfigName: jet-aws-provider-config
    region: us-west-2
  permissionsBoundaryArn: arn:aws:iam::123:policy/crossplaneBoundary
  handler: main
  bucketName: crossplane-serverless
  bucketKey: function.zip
  runTime: go1.x
