apiVersion: awsblueprints.io/v1alpha1
kind: XLambdaFunction
metadata:
  name: test-container-lambda
  namespace: default
spec:
  compositionSelector:
    matchLabels:
      awsblueprints.io/provider: aws-jet
      awsblueprints.io/environment: dev
  resourceConfig:
    providerConfigName: aws-provider-config
    jetProviderConfigName: jet-aws-provider-config
    region: us-west-2
  imageUri: 123.dkr.ecr.us-west-2.amazonaws.com/dummy:0.0.1
  permissionsBoundaryArn: arn:aws:iam::123:policy/crossplaneBoundary