# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

#  Composition and Definition path -> compositions/terrajet-aws-provider/s3
#  This composition creates KMS key and applies to S3 bucket by default

apiVersion: jet.awsblueprints.io/v1alpha1
kind: S3Bucket
metadata:
  name: terra-s3-bucket
  namespace: default
spec:
  compositionSelector:
    matchLabels:
      awsblueprints.io/provider: jet-aws
      awsblueprints.io/environment: dev
      s3.awsblueprints.io/configuration: with-kms
      crossplane.io/xrd: xs3buckets.jet.awsblueprints.io
      service: s3
  resourceConfig:
    name: terra-s3-bucket-123 # S3 bucket name has to be unique
    providerConfigName: jet-aws-provider-config
    region: eu-west-1
    tags:
      env: preprod
      zone: test
      bu: finance
