# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

# Run `kubectl apply -f vpc.yaml` to test this example once you bootstrap the EKS cluster with Crossplane and Terrajet AWS Provider
---
apiVersion: network.awsblueprints.io/v1alpha1
kind: amazonVpc
metadata:
  name: xplane-jet-amazon-vpc
  namespace: default
spec:
  compositionSelector:
    matchLabels:
      awsblueprints.io/provider: jet-aws
      awsblueprints.io/environment: dev
      service: vpc
      compute: managedamazon-vpc
  resourceConfig:
    providerConfigName: jet-aws-provider-config
    region: eu-west-1
  parameters:
    vpcName: jet-aws-provider-vpc
    vpccidrBlock: "10.30.0.0/16"
