# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xs3irsas.awsblueprints.io
spec:
  claimNames:
    kind: S3IRSA
    plural: s3irsas
  group: awsblueprints.io
  names:
    kind: XS3IRSA
    plural: xs3irsas
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          description: S3IRSA is the Schema for the s3irsas API
          properties:
            spec:
              description: S3IRSASpec defines the desired state of S3IRSA
              properties:
                policyArns:
                  items:
                    type: string
                  type: array
                resourceConfig:
                  description: ResourceConfig defines general properties of this AWS
                    resource.
                  properties:
                    deletionPolicy:
                      description: Defaults to Delete
                      enum:
                      - Delete
                      - Orphan
                      type: string
                    name:
                      description: Set the name of this resource in AWS to the value
                        provided by this field.
                      type: string
                    providerConfigName:
                      type: string
                    region:
                      type: string
                    tags:
                      items:
                        properties:
                          key:
                            type: string
                          value:
                            type: string
                        required:
                        - key
                        - value
                        type: object
                      type: array
                  required:
                  - providerConfigName
                  - region
                  type: object
                serviceAccountName:
                  type: string
              required:
              - resourceConfig
              type: object
            status:
              description: S3IRSAStatus defines the observed state of S3IRSA
              properties:
                bucketArn:
                  type: string
                roleName:
                  type: string
              type: object
          type: object
