# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: podidentity.awsblueprints.io
spec:
  compositeTypeRef:
    apiVersion: awsblueprints.io/v1alpha1
    kind: XPodIdentityAssociation
  environment:
    environmentConfigs:
      - type: Reference
        ref:
          name: cluster
  patchSets:
    - name: common-fields-composition
      patches:
        - type: FromCompositeFieldPath
          fromFieldPath: spec.resourceConfig.providerConfigName
          toFieldPath: spec.providerConfigRef.name

          
  resources:
    - name: podidentity-association
      base:
        apiVersion: eks.aws.upbound.io/v1beta1
        kind: PodIdentityAssociation
        #spec:
      patches:            
        - type: PatchSet
          patchSetName: common-fields-composition
        - type: FromCompositeFieldPath
          fromFieldPath: spec.clusterName
          toFieldPath: spec.forProvider.clusterName     
          policy:
            fromFieldPath: Required          
        - type: FromCompositeFieldPath
          fromFieldPath: spec.region
          toFieldPath: spec.forProvider.region     
          policy:
            fromFieldPath: Required          
        - type: FromCompositeFieldPath
          fromFieldPath: spec.roleArn
          toFieldPath: spec.forProvider.roleArn
          policy:
            fromFieldPath: Required          
        - type: FromCompositeFieldPath
          fromFieldPath: spec.serviceAccountName
          toFieldPath: spec.forProvider.serviceAccount    
          policy:
            fromFieldPath: Required
        - type: FromCompositeFieldPath
          fromFieldPath: metadata.labels[crossplane.io/claim-namespace]
          toFieldPath: spec.forProvider.namespace            
      