apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
 - ../../../../compositions/upbound-aws-provider/podidentity/
 - ../../../../compositions/upbound-aws-provider/s3/
 - ../../../../compositions/upbound-aws-provider/s3-podidentity/
