# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0

apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: xdynamoirsa.awsblueprints.io
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
  labels:
    awsblueprints.io/provider: aws
    awsblueprints.io/environment: dev
spec:
  writeConnectionSecretsToNamespace: crossplane-system
  compositeTypeRef:
    apiVersion: awsblueprints.io/v1alpha1
    kind: XDynamoIRSA
  patchSets:
    - name: common-fields-composition
      patches:
        - type: FromCompositeFieldPath
          fromFieldPath: spec.resourceConfig
          toFieldPath: spec.resourceConfig
        - type: FromCompositeFieldPath
          fromFieldPath: spec.dynamoConfig
          toFieldPath: spec.dynamoConfig
  resources:
    - name: dynamodbtable
      connectionDetails:
        - type: FromFieldPath
          name: tableName
          fromFieldPath: status.tableName
      base:
        apiVersion: awsblueprints.io/v1alpha1
        kind: XDynamoDBTable
      patches:
        - type: PatchSet
          patchSetName: common-fields-composition
        - type: ToCompositeFieldPath
          fromFieldPath: status.tableName
          toFieldPath: status.tableName
        - type: ToCompositeFieldPath
          fromFieldPath: status.tableArn
          toFieldPath: status.tableArn
    - name: irsa
      base:
        apiVersion: awsblueprints.io/v1alpha1
        kind: XIRSA
      patches:
        - type: PatchSet
          patchSetName: common-fields-composition
        - type: FromCompositeFieldPath
          fromFieldPath: metadata.labels[crossplane.io/claim-name]
          toFieldPath: spec.serviceAccountName
        - type: ToCompositeFieldPath
          fromFieldPath: status.roleName
          toFieldPath: status.roleName
    - name: irsa-dynamo-policy
      base:
        apiVersion: awsblueprints.io/v1alpha1
        kind: IAMPolicy
        spec:
          compositionSelector:
            matchLabels:
              awsblueprints.io/provider: aws
              awsblueprints.io/environment: dev
              iam.awsblueprints.io/policy-type: write
              iam.awsblueprints.io/service: dynamodb
      patches:
        - type: PatchSet
          patchSetName: common-fields-composition
        - type: FromCompositeFieldPath
          fromFieldPath: status.roleName
          toFieldPath: spec.roleName
        - type: FromCompositeFieldPath
          fromFieldPath: status.tableArn
          toFieldPath: spec.resourceArn
