apiVersion: network.awsblueprints.io/v1alpha1
kind: amazonVpc
metadata:
  name: xplane-amazon-vpc-deny
  namespace: team2
spec:
  resourceConfig:
    providerConfigName: aws-provider-config
  parameters:
    vpcName: us-east-1-acme-team-1 # this should not be allowed since there is already a claim with this value
    vpccidrBlock: "10.20.0.0/16"
    amazonProvidedIpv6CidrBlock: true
