apiVersion: meta.pkg.crossplane.io/v1
kind: Configuration
metadata:
  name: crossplane-aws-blueprints
  annotations:
    friendly-name.meta.crossplane.io: "AWS Blueprints for Crossplane"
    meta.crossplane.io/source: https://github.com/aws-samples/crossplane-aws-blueprints
    meta.crossplane.io/license: MIT-0
    meta.crossplane.io/maintainer: AWS OSS team
    meta.crossplane.io/description: AWS Crossplane Blueprints by the AWS OSS team
    meta.crossplane.io/readme: "AWS Crossplane Blueprints is an open source repo to bootstrap EKS Clusters and provision AWS resources with a library of Crossplane Compositions (XRs) with Composite Resource Definitions (XRDs). Compositions in this repository enable platform teams to define and offer bespoke AWS infrastructure APIs to the teams of application developers based on predefined Composite Resources (XRs), encompassing one or more of AWS Managed Resources (MRs). Note AWS Blueprints for Crossplane is under active development and should be considered a pre-production framework."
spec:
  crossplane:
    version: ">=v1.9.1"
  dependsOn:
    - provider: crossplane/provider-jet-aws
      version: ">=v0.5.0-preview"