
apiVersion: s3.aws.crossplane.io/v1beta1
kind: Bucket
metadata:
  annotations:
    crossplane.io/composition-resource-name: s3-bucket
  labels:
    something: else
  name: standard-object-storage-zlss9-tkqgs
spec:
  deletionPolicy: Delete
  forProvider:
    acl: private
  providerConfigRef:
    name: invalid

