name: Check Markdown links

on:
  push:
    branches:
      - main
    paths:
      - "**/*.md"

  pull_request:
    branches:
      - main
    paths:
      - "**/*.md"

permissions:
  contents: read

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@v2
        with:
          egress-policy: audit

      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29
      - uses: actions/setup-node@v4
        with:
          node-version: '16.x'
      - name: install markdown-link-check
        run: npm install -g markdown-link-check@3.10.2
      - name: markdown-link-check version
        run: npm list -g markdown-link-check
      - name: Run markdown-link-check on MD files
        run: find docs -name "*.md" | xargs -n 1 markdown-link-check -q -c .github/workflows/linkcheck.json